// Generated by https://quicktype.io

export interface Pokemon {
    count: number;
    next: string;
    previous: string;
    results: Result[];
}

export interface Result {
    name: string;
    url: string;
}
